### ISSUE TITLE
alt attributes in img should describe the image

### ISSUE THREAD

**Issue by harysuryanto** [FajarSJ/pokedex#1]
Hello there!

I found that the `alt` in the `<img>` tag doesn't describe what it shows. It would be better If the end users are given the description of the image, especially when the image doesn't show.

![image](https://user-images.githubusercontent.com/17674038/139580082-bd3ed81c-966a-4e48-b5b6-ab43f73bc5dc.png)

**Comment by harysuryanto** [comment]
I would like to fix that issue through contribution

**Comment by fajarsj** [comment]
Hi @harysuryanto, that would be awesome go for it, I'm assigned it to you

**Comment by harysuryanto** [comment]
Thank for assigning me. I have made a PR regarding this issue, please check it out in #2.
